FROM python:3.10-slim

ENV LANG C.UTF-8 \
    TZ 'Asia/Shanghai' 

WORKDIR /app

ADD pandora /app

RUN apk update && apk add --no-cache tzdata \
    && pip install --upgrade pip && pip install '.[api]' \
    && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apk del tzdata

ENTRYPOINT ["pandora"]