name: remove

on:
  push:
    branches:
      - main
  schedule:
    - cron: '12 6 * * 1'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
   
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 10