name: remove

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [auto-remove]

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
   
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 5