name: Auto-Build

on:
  push:
    paths:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
  repository_dispatch:
    types: [docker-build]
  workflow_dispatch:

jobs:

  build_Docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: auto-remove
        token: ${{ secrets.PAT }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get version
      id: version
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/pengzhile/pandora/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

    # - name: 获取最新仓库文件
    #   run: |
    #     echo ${{ steps.version.outputs.latest_tag }}
    #     git clone https://github.com/pengzhile/pandora.git

    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     platforms: linux/amd64
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKER_USERNAME }}/pandora:amd64

    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     file: ./Dockerfile_arm
    #     platforms: linux/arm64
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKER_USERNAME }}/pandora:arm64

    # - name: 创建版本号列表
    #   run: |
        
    #     docker manifest create ${{ secrets.DOCKER_USERNAME }}/pandora:${{ steps.version.outputs.latest_tag }} \
    #       ${{ secrets.DOCKER_USERNAME }}/pandora:arm64 \
    #       ${{ secrets.DOCKER_USERNAME }}/pandora:amd64

    # - name: 设置版本号列表
    #   run: |
    #     docker manifest annotate ${{ secrets.DOCKER_USERNAME }}/pandora:${{ steps.version.outputs.latest_tag }} \
    #       ${{ secrets.DOCKER_USERNAME }}/pandora:arm64 \
    #       --os linux --arch arm64 --variant v8
    #     docker manifest annotate ${{ secrets.DOCKER_USERNAME }}/pandora:${{ steps.version.outputs.latest_tag }} \
    #       ${{ secrets.DOCKER_USERNAME }}/pandora:amd64 \
    #       --os linux --arch amd64

    # - name: 推送版本号列表
    #   run: docker manifest push ${{ secrets.DOCKER_USERNAME }}/pandora:${{ steps.version.outputs.latest_tag }}

    - name: 创建 latest 列表
      run: |
        docker manifest create ${{ secrets.DOCKER_USERNAME }}/pandora:latest \
          ${{ secrets.DOCKER_USERNAME }}/pandora:amd64 \
          ${{ secrets.DOCKER_USERNAME }}/pandora:arm64

    - name: 设置latest列表
      run: |
        docker manifest annotate ${{ secrets.DOCKER_USERNAME }}/pandora:latest \
          ${{ secrets.DOCKER_USERNAME }}/pandora:amd64 --os linux --arch amd64
        docker manifest annotate ${{ secrets.DOCKER_USERNAME }}/pandora:latest \
          ${{ secrets.DOCKER_USERNAME }}/pandora:arm64 --os linux --arch arm64

    - name: 推送latest列表
      run: docker manifest push ${{ secrets.DOCKER_USERNAME }}/pandora:latest