name: Auto-Build

on:
  push:
    paths:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
  repository_dispatch:
    types: [docker-build]

jobs:

  build_Docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: auto-remove
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get Date
      id: date
      run: |
        TZ=Asia/Shanghai
        echo "time=$(date +'%m-%d')" >> $GITHUB_OUTPUT

    - name: 获取最新仓库文件
      run: |
        echo ${{ steps.date.outputs.date }}
        git clone https://github.com/pengzhile/pandora.git

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/pandora
          ${{ secrets.DOCKER_USERNAME }}/pandora:${{ steps.date.outputs.time }}