name: Auto-Build

on:
  push:
    paths:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
    repositories:
      - owner: pandora
        name: pengzhile

jobs:

  build_Docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      # with:
      #   version: v0.9.1

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get Date
      id: date
      run: |
        TZ=Asia/Shanghai
        echo "::set-output name=date::$(date +'%m-%d')"

    - name: 获取最新仓库文件
      run: git clone https://github.com/pengzhile/pandora.git

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/pandora
          ${{ secrets.DOCKER_USERNAME }}/pandora:

  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 5