name: Auto-Build

on:
  push:
    paths:
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
  repository_dispatch:
    types: [docker-build]

jobs:

  build_Docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: auto-remove
        token: ${{ secrets.PAT }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Get Date
    #   id: date
    #   run: |
    #     TZ=Asia/Shanghai
    #     echo "time=$(date +'%m-%d')" >> $GITHUB_OUTPUT

    - name: Get version
      id: version
      run: |
        echo "version=$(curl -s https://api.github.com/repos/pengzhile/pandora/releases/latest | cut -d'"' -f4)" >> GITHUB_OUTPUT

    - name: 获取最新仓库文件
      run: |
        echo ${{ steps.version.outputs.version }}
        git clone https://github.com/pengzhile/pandora.git

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/pandora
          ${{ secrets.DOCKER_USERNAME }}/pandora:${{ steps.version.outputs.version }}